import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ILayoutProps } from "@/types";

export const metadata: Metadata = {
  title: "Next stripe ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ILayoutProps) {
  return (
    <html lang="en">
      <body className="flex min-h-full flex-col bg-white">
        <Navbar />

        <main className="flex-grow container mx-auto px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
